app/vmauth: expose built-in handlers if `-httpInternalListenAddr` is specified (#8902)
This functionality was broken in
https://github.com/VictoriaMetrics/VictoriaMetrics/commit/0e313e53557f01046e3162abb33ef361ccf4a243

Was caught by integration tests:
```
--- FAIL: TestSingleVMAuthRouterWithInternalAddr (5.00s)
    vmauth_routing_test.go:148: Could not start vmauth: could not extract some or all regexps from stderr: ["pprof handlers are exposed at http://(.*:\\d{1,5})/debug/pprof/"]
```

Signed-off-by: hagen1778 <roman@victoriametrics.com>
(cherry picked from commit e77df5d00ba4c95c7156ef5db89909375eb026b7)