app/vmselect: fix tenant filtering with long tenant regexp
When tenant filter is a long regexp, its content can be replaced with
`...`, causing tenants to be matched incorrectly.

`applyFiltersToTenants` converts tag filters using `tagFiltersToString`

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/c497c8c2e90962f5d77785d4333287d978cd2d1b/app/vmselect/netstorage/tenant_filters.go#L106-L112

Which uses human-readable representation of `TagFilter`

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/c497c8c2e90962f5d77785d4333287d978cd2d1b/lib/storage/search.go#L390-L397

This way I can see results from unexpected tenants. See the test, which
fails with
```
--- FAIL: TestApplyFiltersToTenants (0.00s)
    tenant_filters_test.go:18: unexpected tenants result; got [{100 0} {116 0} {1239 0}]; want [{100 0} {108 0} {116 0}]
```

---------

Related PR https://github.com/VictoriaMetrics/VictoriaMetrics/pull/11096