lib/protoparser/opentelemetry: fix typo in code
#
github.com/VictoriaMetrics/VictoriaMetrics/lib/protoparser/opentelemetry/pb
lib/protoparser/opentelemetry/pb/pb.go:1683:19: undefined: lctx

Bug introduced in
https://github.com/VictoriaMetrics/VictoriaMetrics/commit/1dc71212f8e3712090567c86b6fbdc154cd8a8a4